# Uplift configuration for semantic versioning
# Documentation: https://uplift.run/

# Semantic versioning bumps based on commit types
bumps:
  - regex:
      - "BREAKING CHANGE"
      - "!:"
    type: "major"
  
  - regex:
      - "^feat"
      - "^feature"
    type: "minor"
    
  - regex:
      - "^fix"
      - "^chore" 
      - "^docs"
      - "^style"
      - "^refactor"
      - "^perf"
      - "^test"
      - "^ci"
      - "^build"
    type: "patch"

# Git configuration
git:
  ignoreDetached: false

# Environment variables
env:
  GITHUB_TOKEN: true