# Uplift configuration for semantic versioning
# Documentation: https://upliftci.dev/

# File-based version bumping
bumps:
  - file: go.mod
    regex: ^module
    
# Git configuration  
git:
  ignoreDetached: false

# Semantic versioning based on commit messages
commits:
  major:
    - "BREAKING CHANGE"
    - "!:"
  minor:
    - "feat"
    - "feature"
  patch:
    - "fix" 
    - "chore"
    - "docs"
    - "style"
    - "refactor"
    - "perf"
    - "test"
    - "ci"
    - "build"